### ISSUE TITLE
Add more than one domain?

### ISSUE THREAD

**Issue by skrause-data** [lfhohmann/ha-duckdns_ipv4_ipv6#2]
Hi,

I am using 3 different sub domains for my DuckDNS account. With the standard Addon it is easiely possible to add several sub domains in the configuration.yaml. Does adding multiple sub domains work in your addon, too?

**Comment by RuessAar** [comment]
Hey, 

I second this. It would be best if the domain Part, would be able to take a list as input.

**Comment by RuessAar** [comment]
After revisiting the duckdns documentation and trying a few things I have found that you can just add multiple domains separated by commas. Important is to leave no spaces between the domains and comma.

Example:
```
duckdns_ipv4_ipv6:
  access_token: YOUR_ACCESS_TOKEN
  domain: YOUR_SUBDOMAIN_1,YOUR_SUBDOMAIN_2
  ipv4_mode: duckdns
  ipv6_mode: nameserver
```
